name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
       submodules: true

    - name: Update Distro
      run: sudo apt-get update
      
    - name: Install Libraries Prerequisites
      run: sudo apt-get install xorg-dev libglu1-mesa-dev
      
    - name: Setup Python
      uses: actions/setup-python@v4.6.0
      with:
        python-version: '3.10' 

    - name: Setup Python requests
      run: sudo pip3 install requests

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
       vulkan-query-version: 1.3.204.0
       vulkan-components: Vulkan-Headers, Vulkan-Loader
       vulkan-use-cache: true
       
    - name: Download & Install external libraries
      run: python scripts/download_prerequisite.py

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/.build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build - ${{env.BUILD_TYPE}}
      run: cmake --build ${{github.workspace}}/.build
